const BET_CONFIG = {
  user: {
    id: "5c332b8e-4b3f-4778-93a4-a63997d8844c",
    username: "huy_user1",
    email: "huy_user1@gmail.com",
    full_name: "Huy User 1",
    role_id: 3,
    created_by: "d9b00195-a16e-46c5-a9a1-0b22e6929a13",
    is_active: true,
    created_at: "2025-04-08T09:07:13.889513+00:00",
    updated_at: "2025-04-09T14:48:16.893039+00:00",
  },
  accessibleStations: [
    {
      id: 1,
      name: "TP. HCM",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: [
        "tp",
        "tpho",
        "thanh pho",
        "hcm",
        "tp hcm",
        "thanh pho ho chi minh",
        "thành phố hồ chí minh",
        "thanh pho hcm",
        "thành phố hcm",
        "hồ chí minh",
        "ho chi minh",
        "saigon",
        "sài gòn",
        "sg",
      ],
      is_active: true,
      region_id: 3,
    },
    {
      id: 2,
      name: "Đồng Tháp",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["dt", "dthap", "dongthap", "dong thap", "đồng tháp"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 3,
      name: "Cà Mau",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["cm", "cmau", "camau", "ca mau", "cà mau"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 4,
      name: "Bến Tre",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["bt", "btre", "bentre", "ben tre", "bến tre"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 5,
      name: "Vũng Tàu",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["vt", "vtau", "vungtau", "vung tau", "vũng tàu"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 6,
      name: "Bạc Liêu",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["bl", "blieu", "baclieu", "bac lieu", "bạc liêu"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 7,
      name: "Đồng Nai",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["dnai", "dongnai", "dong nai", "đồng nai"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 8,
      name: "Cần Thơ",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["ct", "ctho", "cantho", "can tho", "cần thơ"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 9,
      name: "Sóc Trăng",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["st", "strang", "soctrang", "soc trang", "sóc trăng"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 10,
      name: "Tây Ninh",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["tn", "tninh", "tayninh", "tay ninh", "tây ninh"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 12,
      name: "Bình Thuận",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["bthuan", "binhthuan", "binh thuan", "bình thuận"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 13,
      name: "Vĩnh Long",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["vl", "vlong", "vinhlong", "vinh long", "vĩnh long"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 14,
      name: "Bình Dương",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["bd", "bduong", "binhduong", "binh duong", "bình dương"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 15,
      name: "Trà Vinh",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["tv", "tvinh", "travinh", "tra vinh", "trà vinh"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 16,
      name: "Long An",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["la", "lan", "longan", "long an"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 17,
      name: "Bình Phước",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["bp", "bphuoc", "binhphuoc", "binh phuoc", "bình phước"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 18,
      name: "Hậu Giang",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["hg", "hgiang", "haugiang", "hau giang", "hậu giang"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 19,
      name: "Tiền Giang",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["tg", "tgiang", "tiengiang", "tien giang", "tiền giang"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 20,
      name: "Kiên Giang",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["kg", "kgiang", "kiengiang", "kien giang", "kiên giang"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 21,
      name: "Đà Lạt",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["dl", "dlat", "dalat", "da lat", "đà lạt"],
      is_active: true,
      region_id: 3,
    },
    {
      id: 22,
      name: "Đà Nẵng",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["dn", "dnang", "danang", "da nang", "đà nẵng"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 23,
      name: "Quảng Nam",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["qn", "qnam", "quangnam", "quang nam", "quảng nam"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 24,
      name: "Đắk Lắk",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["dl", "dlak", "daklak", "dak lak", "đắk lắk"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 25,
      name: "Khánh Hòa",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["kh", "khoa", "khanhhoa", "khanh hoa", "khánh hòa"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 26,
      name: "Thừa Thiên Huế",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: [
        "hue",
        "tthue",
        "thuathienhue",
        "thua thien hue",
        "thừa thiên huế",
      ],
      is_active: true,
      region_id: 2,
    },
    {
      id: 27,
      name: "Phú Yên",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["py", "pyen", "phuyen", "phu yen", "phú yên"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 29,
      name: "Quảng Trị",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["qt", "qtri", "quangtri", "quang tri", "quảng trị"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 30,
      name: "Quảng Bình",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["qb", "qbinh", "quangbinh", "quang binh", "quảng bình"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 31,
      name: "Gia Lai",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["gl", "glai", "gialai", "gia lai"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 32,
      name: "Ninh Thuận",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["nt", "nthuan", "ninhthuan", "ninh thuan", "ninh thuận"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 33,
      name: "Quảng Ngãi",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["qngai", "quangngai", "quang ngai", "quảng ngãi"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 34,
      name: "Đắk Nông",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["dn", "dnong", "daknong", "dak nong", "đắk nông"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 35,
      name: "Kon Tum",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["kt", "ktum", "kontum", "kon tum"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 36,
      name: "Miền Bắc",
      region: {
        id: 1,
        code: "north",
        name: "Miền Bắc",
        aliases: [
          "mb",
          "mienbac",
          "miền bắc",
          "hanoi",
          "hn",
          "hà nội",
          "daibac",
          "dbac",
          "đài bắc",
          "đài miền bắc",
          "db",
        ],
      },
      aliases: [
        "mb",
        "mienbac",
        "miền bắc",
        "hanoi",
        "hn",
        "hà nội",
        "daibac",
        "dbac",
        "đài bắc",
        "đài miền bắc",
        "db",
      ],
      is_active: true,
      region_id: 1,
    },
    {
      id: 37,
      name: "Hà Nội",
      region: {
        id: 1,
        code: "north",
        name: "Miền Bắc",
        aliases: [
          "mb",
          "mienbac",
          "miền bắc",
          "hanoi",
          "hn",
          "hà nội",
          "daibac",
          "dbac",
          "đài bắc",
          "đài miền bắc",
          "db",
        ],
      },
      aliases: ["hanoi", "hn", "hà nội"],
      is_active: true,
      region_id: 1,
    },
    {
      id: 38,
      name: "Quảng Ninh",
      region: {
        id: 1,
        code: "north",
        name: "Miền Bắc",
        aliases: [
          "mb",
          "mienbac",
          "miền bắc",
          "hanoi",
          "hn",
          "hà nội",
          "daibac",
          "dbac",
          "đài bắc",
          "đài miền bắc",
          "db",
        ],
      },
      aliases: ["qn", "qninh", "quangninh", "quang ninh", "quảng ninh"],
      is_active: true,
      region_id: 1,
    },
    {
      id: 39,
      name: "Bắc Ninh",
      region: {
        id: 1,
        code: "north",
        name: "Miền Bắc",
        aliases: [
          "mb",
          "mienbac",
          "miền bắc",
          "hanoi",
          "hn",
          "hà nội",
          "daibac",
          "dbac",
          "đài bắc",
          "đài miền bắc",
          "db",
        ],
      },
      aliases: ["bn", "bninh", "bacninh", "bac ninh", "bắc ninh"],
      is_active: true,
      region_id: 1,
    },
    {
      id: 40,
      name: "Hải Phòng",
      region: {
        id: 1,
        code: "north",
        name: "Miền Bắc",
        aliases: [
          "mb",
          "mienbac",
          "miền bắc",
          "hanoi",
          "hn",
          "hà nội",
          "daibac",
          "dbac",
          "đài bắc",
          "đài miền bắc",
          "db",
        ],
      },
      aliases: ["hp", "hphong", "haiphong", "hai phong", "hải phòng"],
      is_active: true,
      region_id: 1,
    },
    {
      id: 41,
      name: "Nam Định",
      region: {
        id: 1,
        code: "north",
        name: "Miền Bắc",
        aliases: [
          "mb",
          "mienbac",
          "miền bắc",
          "hanoi",
          "hn",
          "hà nội",
          "daibac",
          "dbac",
          "đài bắc",
          "đài miền bắc",
          "db",
        ],
      },
      aliases: ["nd", "ndinh", "namdinh", "nam dinh", "nam định"],
      is_active: true,
      region_id: 1,
    },
    {
      id: 42,
      name: "Thái Bình",
      region: {
        id: 1,
        code: "north",
        name: "Miền Bắc",
        aliases: [
          "mb",
          "mienbac",
          "miền bắc",
          "hanoi",
          "hn",
          "hà nội",
          "daibac",
          "dbac",
          "đài bắc",
          "đài miền bắc",
          "db",
        ],
      },
      aliases: ["tb", "tbinh", "thaibinh", "thai binh", "thái bình"],
      is_active: true,
      region_id: 1,
    },
    {
      id: 28,
      name: "Bình Định",
      region: {
        id: 2,
        code: "central",
        name: "Miền Trung",
        aliases: [
          "mt",
          "dmt",
          "dt",
          "dtrung",
          "mientrung",
          "mien trung",
          "miền trung",
          "đài trung",
          "đài miền trung",
          "mtrung",
        ],
      },
      aliases: ["bd", "bdinh", "binhdinh", "binh dinh", "bình định"],
      is_active: true,
      region_id: 2,
    },
    {
      id: 11,
      name: "An Giang",
      region: {
        id: 3,
        code: "south",
        name: "Miền Nam",
        aliases: [
          "mn",
          "dmn",
          "dn",
          "dnam",
          "miennam",
          "mien nam",
          "miền nam",
          "đài nam",
          "đài miền nam",
          "mnam",
        ],
      },
      aliases: ["ag", "agiang", "angiang", "an giang"],
      is_active: true,
      region_id: 3,
    },
  ],
  regions: [
    {
      id: 1,
      name: "Miền Bắc",
      code: "north",
      aliases: [
        "mb",
        "mienbac",
        "miền bắc",
        "hanoi",
        "hn",
        "hà nội",
        "daibac",
        "dbac",
        "đài bắc",
        "đài miền bắc",
        "db",
      ],
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 2,
      name: "Miền Trung",
      code: "central",
      aliases: [
        "mt",
        "dmt",
        "dt",
        "dtrung",
        "mientrung",
        "mien trung",
        "miền trung",
        "đài trung",
        "đài miền trung",
        "mtrung",
      ],
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 3,
      name: "Miền Nam",
      code: "south",
      aliases: [
        "mn",
        "dmn",
        "dn",
        "dnam",
        "miennam",
        "mien nam",
        "miền nam",
        "đài nam",
        "đài miền nam",
        "mnam",
      ],
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
  ],
  betTypes: [
    {
      id: 2,
      name: "Xỉu chủ",
      aliases: ["xc", "x", "xiu chu", "xiuchu", "three digits"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["3 digits"],
      matching_method: "Match the last 3 digits of the draw",
      payout_rate: 650,
      combinations: {
        north: 4,
        south: 2,
        central: 2,
      },
      is_permutation: false,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 650,
    },
    {
      id: 3,
      name: "Đầu",
      aliases: ["dau", "đầu", "head"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["2 digits", "3 digits"],
      matching_method: "Match the last 2 or 3 digits of the draw",
      payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
      },
      combinations: {
        "2 digits": {
          north: 4,
          south: 1,
          central: 1,
        },
        "3 digits": {
          north: 3,
          south: 1,
          central: 1,
        },
      },
      is_permutation: false,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
      },
    },
    {
      id: 4,
      name: "Đuôi",
      aliases: ["duoi", "dui", "đuôi", "tail"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["2 digits", "3 digits"],
      matching_method: "Match the last 2 or 3 digits of the draw",
      payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
      },
      combinations: {
        "2 digits": {
          north: 1,
          south: 1,
          central: 1,
        },
        "3 digits": {
          north: 1,
          south: 1,
          central: 1,
        },
      },
      is_permutation: false,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
      },
    },
    {
      id: 6,
      name: "Đảo Bao Lô",
      aliases: ["daob", "bdao", "dao bao", "dao bao lo", "permutation cover"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["2 digits", "3 digits"],
      matching_method: "Match any permutation of the last N digits of the draw",
      payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
      },
      combinations: {
        "2 digits": {
          north: 27,
          south: 18,
          central: 18,
        },
        "3 digits": {
          north: 23,
          south: 17,
          central: 17,
        },
      },
      is_permutation: true,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
      },
    },
    {
      id: 7,
      name: "Bao Lô 7",
      aliases: ["baobay", "b7l", "b7lo", "bao lo 7", "cover seven"],
      applicable_regions: ["south", "central"],
      bet_rule: ["2 digits"],
      matching_method: "Match the last 2 digits of specific prizes",
      payout_rate: 75,
      combinations: {
        south: 7,
        central: 7,
      },
      is_permutation: false,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 75,
    },
    {
      id: 8,
      name: "Bao Lô 8",
      aliases: ["baotam", "b8l", "b8lo", "bao lo 8", "cover eight"],
      applicable_regions: ["north"],
      bet_rule: ["2 digits"],
      matching_method: "Match the last 2 digits of specific prizes",
      payout_rate: 75,
      combinations: {
        north: 8,
      },
      is_permutation: false,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 75,
    },
    {
      id: 9,
      name: "Bao Lô 7 Đảo",
      aliases: ["b7ld", "b7ldao", "cover seven permutation"],
      applicable_regions: ["south", "central"],
      bet_rule: ["2 digits"],
      matching_method:
        "Match any permutation of the last 2 digits of specific prizes",
      payout_rate: 75,
      combinations: {
        south: 7,
        central: 7,
      },
      is_permutation: true,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 75,
    },
    {
      id: 10,
      name: "Bao Lô 8 Đảo",
      aliases: ["b8ld", "b8ldao", "cover eight permutation"],
      applicable_regions: ["north"],
      bet_rule: ["2 digits"],
      matching_method:
        "Match any permutation of the last 2 digits of specific prizes",
      payout_rate: 75,
      combinations: {
        north: 8,
      },
      is_permutation: true,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 75,
    },
    {
      id: 11,
      name: "Đá",
      aliases: ["da", "dv"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["2 digits"],
      matching_method: "At least 2 betted numbers match the draw",
      payout_rate: {
        bridgeNorth: 650,
        bridgeOneStation: 750,
        bridgeTwoStations: 550,
      },
      combinations: {
        north: 27,
        south: 18,
        central: 18,
      },
      is_permutation: false,
      special_calc: "bridge",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: {
        bridgeNorth: 650,
        bridgeOneStation: 750,
        bridgeTwoStations: 550,
      },
    },
    {
      id: 12,
      name: "Đảo Xỉu Chủ",
      aliases: ["daoxc", "dxc", "xcd", "xcdao", "permutation three digits"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["3 digits"],
      matching_method: "Match any permutation of the last 3 digits of the draw",
      payout_rate: 650,
      combinations: {
        north: 4,
        south: 2,
        central: 2,
      },
      is_permutation: true,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 650,
    },
    {
      id: 13,
      name: "Đảo Xỉu Chủ Đầu",
      aliases: ["dxcdau", "daodau", "ddau", "permutation head"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["3 digits"],
      matching_method:
        "Match any permutation of the last 3 digits of the head prize",
      payout_rate: 650,
      combinations: {
        north: 3,
        south: 1,
        central: 1,
      },
      is_permutation: true,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 650,
    },
    {
      id: 14,
      name: "Đảo Xỉu Chủ Đuôi",
      aliases: [
        "dxcduoi",
        "daoduoi",
        "daodui",
        "dduoi",
        "ddui",
        "permutation tail",
      ],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["3 digits"],
      matching_method:
        "Match any permutation of the last 3 digits of the special prize",
      payout_rate: 650,
      combinations: {
        north: 1,
        south: 1,
        central: 1,
      },
      is_permutation: true,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 650,
    },
    {
      id: 15,
      name: "Nhất To",
      aliases: ["nt", "nto", "nhatto", "first prize"],
      applicable_regions: ["north"],
      bet_rule: ["2 digits", "3 digits", "4 digits"],
      matching_method: "Match the last N digits of the first prize",
      payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
        "4 digits": 5500,
      },
      combinations: {
        north: 1,
      },
      is_permutation: false,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
        "4 digits": 5500,
      },
    },
    {
      id: 1,
      name: "Đầu Đuôi",
      aliases: ["dd", "dau duoi", "đầu đuôi", "head and tail"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["2 digits"],
      matching_method: "Match the last 2 digits of the draw",
      payout_rate: 75,
      combinations: {
        north: 5,
        south: 2,
        central: 2,
      },
      is_permutation: false,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:08:24.159394+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: 75,
    },
    {
      id: 5,
      name: "Bao Lô",
      aliases: ["b", "bao", "bao lo", "bao lô", "cover all"],
      applicable_regions: ["south", "central", "north"],
      bet_rule: ["2 digits", "3 digits", "4 digits"],
      matching_method: "Match the last 2, 3, or 4 digits of the draw",
      payout_rate: {
        "2 digits": 75,
        "3 digits": 650,
        "4 digits": 5500,
      },
      combinations: {
        "2 digits": {
          north: 27,
          south: 18,
          central: 18,
        },
        "3 digits": {
          north: 23,
          south: 17,
          central: 17,
        },
        "4 digits": {
          north: 20,
          south: 16,
          central: 16,
        },
      },
      is_permutation: false,
      special_calc: null,
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-09T04:18:10.284617+00:00",
      multiplier: 1,
      is_active_for_user: true,
      custom_payout_rate: {
        "2 digits": 100,
        "3 digits": 650,
        "4 digits": 5500,
      },
    },
  ],
  numberCombinations: [
    {
      id: 1,
      name: "Kéo",
      aliases: ["keo", "sequence"],
      definition:
        "Chọn số bắt đầu, số tiếp theo và số kết thúc để tạo một dãy số",
      syntax: "[startNumber]/[nextNumber]keo[endNumber]",
      applicable_bet_types: ["dau", "duoi", "dd", "xc"],
      examples: [
        "10/20keo90 (sequence: 10, 20, 30, 40, 50, 60, 70, 80, 90)",
        "10/11keo19 (sequence: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)",
        "111/222keo999 (sequence: 111, 222, 333, 444, 555, 666, 777, 888, 999)",
      ],
      calculation_method:
        "Let startNumber=A, nextNumber=B, endNumber=C. Step size D = B-A. Number of variations = (C-A)/D + 1",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 2,
      name: "Tài",
      aliases: ["tai", "high"],
      definition: "Bao gồm 50 số từ 50 đến 99",
      syntax: "tai",
      applicable_bet_types: ["dau", "duoi", "dd"],
      examples: ["tai (numbers: 50, 51, 52, ..., 99)"],
      calculation_method: "Fixed set of 50 numbers from 50 to 99",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 3,
      name: "Xỉu",
      aliases: ["xiu", "low"],
      definition: "Bao gồm 50 số từ 00 đến 49",
      syntax: "xiu",
      applicable_bet_types: ["dau", "duoi", "dd"],
      examples: ["xiu (numbers: 00, 01, 02, ..., 49)"],
      calculation_method: "Fixed set of 50 numbers from 00 to 49",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 4,
      name: "Chẵn",
      aliases: ["chan", "even"],
      definition: "Bao gồm 50 số chẵn từ 00 đến 98",
      syntax: "chan",
      applicable_bet_types: ["dau", "duoi", "dd"],
      examples: ["chan (numbers: 00, 02, 04, ..., 98)"],
      calculation_method: "Fixed set of 50 even numbers from 00 to 98",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 5,
      name: "Lẻ",
      aliases: ["le", "odd"],
      definition: "Bao gồm 50 số lẻ từ 01 đến 99",
      syntax: "le",
      applicable_bet_types: ["dau", "duoi", "dd"],
      examples: ["le (numbers: 01, 03, 05, ..., 99)"],
      calculation_method: "Fixed set of 50 odd numbers from 01 to 99",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 6,
      name: "Chẵn Chẵn",
      aliases: ["chanchan", "even-even"],
      definition: "Bao gồm 25 số có cả hai chữ số đều chẵn",
      syntax: "chanchan",
      applicable_bet_types: ["dau", "duoi", "dd"],
      examples: [
        "chanchan (numbers: 00, 02, 04, 06, 08, 20, 22, 24, 26, 28, ...)",
      ],
      calculation_method: "Fixed set of 25 numbers where both digits are even",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 7,
      name: "Lẻ Lẻ",
      aliases: ["lele", "odd-odd"],
      definition: "Bao gồm 25 số có cả hai chữ số đều lẻ",
      syntax: "lele",
      applicable_bet_types: ["dau", "duoi", "dd"],
      examples: ["lele (numbers: 11, 13, 15, 17, 19, 31, 33, 35, 37, 39, ...)"],
      calculation_method: "Fixed set of 25 numbers where both digits are odd",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 8,
      name: "Chẵn Lẻ",
      aliases: ["chanle", "even-odd"],
      definition: "Bao gồm 25 số có chữ số đầu là chẵn và chữ số thứ hai là lẻ",
      syntax: "chanle",
      applicable_bet_types: ["dau", "duoi", "dd"],
      examples: [
        "chanle (numbers: 01, 03, 05, 07, 09, 21, 23, 25, 27, 29, ...)",
      ],
      calculation_method:
        "Fixed set of 25 numbers where first digit is even and second digit is odd",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
    {
      id: 9,
      name: "Lẻ Chẵn",
      aliases: ["lechan", "odd-even"],
      definition: "Bao gồm 25 số có chữ số đầu là lẻ và chữ số thứ hai là chẵn",
      syntax: "lechan",
      applicable_bet_types: ["dau", "duoi", "dd"],
      examples: [
        "lechan (numbers: 10, 12, 14, 16, 18, 30, 32, 34, 36, 38, ...)",
      ],
      calculation_method:
        "Fixed set of 25 numbers where first digit is odd and second digit is even",
      is_active: true,
      created_at: "2025-04-07T05:47:11.4208+00:00",
      updated_at: "2025-04-07T05:47:11.4208+00:00",
    },
  ],
  commissionSettings: {
    priceRate: 0.81,
    exportPriceRate: 0.75,
    returnPriceRate: 0.96,
  },
};
