// src/config/defaults.js
export const defaultStations = [
  // Miền Nam
  {
    name: 'TP. HCM',
    region: 'south',
    aliases: [
      'hcm',
      'tp hcm',
      'thanh pho ho chi minh',
      'thành phố hồ chí minh',
      'thanh pho hcm',
      'thành phố hcm',
      'hồ chí minh',
      'ho chi minh',
      'tp',
      'tpho',
      'saigon',
      'sài gòn',
      'sg',
    ],
    isActive: true,
    schedule: [
      { day: 'monday', order: 1 },
      { day: 'saturday', order: 1 },
    ],
  },
  {
    name: 'Đồng Tháp',
    region: 'south',
    aliases: ['dt', 'dthap', 'dongthap', 'dong thap', 'đồng tháp'],
    isActive: true,
    schedule: { day: 'monday', order: 2 },
  },
  {
    name: 'Cà Mau',
    region: 'south',
    aliases: ['cm', 'cmau', 'camau', 'ca mau', 'cà mau'],
    isActive: true,
    schedule: { day: 'monday', order: 3 },
  },
  {
    name: 'Bến Tre',
    region: 'south',
    aliases: ['bt', 'btre', 'bentre', 'ben tre', 'bến tre'],
    isActive: true,
    schedule: { day: 'tuesday', order: 1 },
  },
  {
    name: 'Vũng Tàu',
    region: 'south',
    aliases: ['vt', 'vtau', 'vungtau', 'vung tau', 'vũng tàu'],
    isActive: true,
    schedule: { day: 'tuesday', order: 2 },
  },
  {
    name: 'Bạc Liêu',
    region: 'south',
    aliases: ['bl', 'blieu', 'baclieu', 'bac lieu', 'bạc liêu'],
    isActive: true,
    schedule: { day: 'tuesday', order: 3 },
  },
  {
    name: 'Đồng Nai',
    region: 'south',
    aliases: ['dnai', 'dongnai', 'dong nai', 'đồng nai'],
    isActive: true,
    schedule: { day: 'wednesday', order: 1 },
  },
  {
    name: 'Cần Thơ',
    region: 'south',
    aliases: ['ct', 'ctho', 'cantho', 'can tho', 'cần thơ'],
    isActive: true,
    schedule: { day: 'wednesday', order: 2 },
  },
  {
    name: 'Sóc Trăng',
    region: 'south',
    aliases: ['st', 'strang', 'soctrang', 'soc trang', 'sóc trăng'],
    isActive: true,
    schedule: { day: 'wednesday', order: 3 },
  },
  {
    name: 'Tây Ninh',
    region: 'south',
    aliases: ['tn', 'tninh', 'tayninh', 'tay ninh', 'tây ninh'],
    isActive: true,
    schedule: { day: 'thursday', order: 1 },
  },
  {
    name: 'An Giang',
    region: 'south',
    aliases: ['ag', 'agiang', 'angiang', 'an giang'],
    isActive: true,
    schedule: { day: 'thursday', order: 2 },
  },
  {
    name: 'Bình Thuận',
    region: 'south',
    aliases: ['bthuan', 'binhthuan', 'binh thuan', 'bình thuận'],
    isActive: true,
    schedule: { day: 'thursday', order: 3 },
  },
  {
    name: 'Vĩnh Long',
    region: 'south',
    aliases: ['vl', 'vlong', 'vinhlong', 'vinh long', 'vĩnh long'],
    isActive: true,
    schedule: { day: 'friday', order: 1 },
  },
  {
    name: 'Bình Dương',
    region: 'south',
    aliases: ['bd', 'bduong', 'binhduong', 'binh duong', 'bình dương'],
    isActive: true,
    schedule: { day: 'friday', order: 2 },
  },
  {
    name: 'Trà Vinh',
    region: 'south',
    aliases: ['tv', 'tvinh', 'travinh', 'tra vinh', 'trà vinh'],
    isActive: true,
    schedule: { day: 'friday', order: 3 },
  },
  {
    name: 'Long An',
    region: 'south',
    aliases: ['la', 'lan', 'longan', 'long an'],
    isActive: true,
    schedule: { day: 'saturday', order: 2 },
  },
  {
    name: 'Bình Phước',
    region: 'south',
    aliases: ['bp', 'bphuoc', 'binhphuoc', 'binh phuoc', 'bình phước'],
    isActive: true,
    schedule: { day: 'saturday', order: 3 },
  },
  {
    name: 'Hậu Giang',
    region: 'south',
    aliases: ['hg', 'hgiang', 'haugiang', 'hau giang', 'hậu giang'],
    isActive: true,
    schedule: { day: 'saturday', order: 4 },
  },
  {
    name: 'Tiền Giang',
    region: 'south',
    aliases: ['tg', 'tgiang', 'tiengiang', 'tien giang', 'tiền giang'],
    isActive: true,
    schedule: { day: 'sunday', order: 1 },
  },
  {
    name: 'Kiên Giang',
    region: 'south',
    aliases: ['kg', 'kgiang', 'kiengiang', 'kien giang', 'kiên giang'],
    isActive: true,
    schedule: { day: 'sunday', order: 2 },
  },
  {
    name: 'Đà Lạt',
    region: 'south',
    aliases: ['dl', 'dlat', 'dalat', 'da lat', 'đà lạt'],
    isActive: true,
    schedule: { day: 'sunday', order: 3 },
  },

  // Miền Trung
  {
    name: 'Đà Nẵng',
    region: 'central',
    aliases: ['dn', 'dnang', 'danang', 'da nang', 'đà nẵng'],
    isActive: true,
    schedule: [
      { day: 'wednesday', order: 1 },
      { day: 'saturday', order: 1 },
    ],
  },
  {
    name: 'Quảng Nam',
    region: 'central',
    aliases: ['qn', 'qnam', 'quangnam', 'quang nam', 'quảng nam'],
    isActive: true,
    schedule: { day: 'tuesday', order: 2 },
  },
  {
    name: 'Đắk Lắk',
    region: 'central',
    aliases: ['dl', 'dlak', 'daklak', 'dak lak', 'đắk lắk'],
    isActive: true,
    schedule: { day: 'tuesday', order: 1 },
  },
  {
    name: 'Khánh Hòa',
    region: 'central',
    aliases: ['kh', 'khoa', 'khanhhoa', 'khanh hoa', 'khánh hòa'],
    isActive: true,
    schedule: [
      { day: 'wednesday', order: 2 },
      { day: 'sunday', order: 2 },
    ],
  },
  {
    name: 'Thừa Thiên Huế',
    region: 'central',
    aliases: [
      'hue',
      'tthue',
      'thuathienhue',
      'thua thien hue',
      'thừa thiên huế',
    ],
    isActive: true,
    schedule: [
      { day: 'monday', order: 2 },
      { day: 'sunday', order: 3 },
    ],
  },
  {
    name: 'Phú Yên',
    region: 'central',
    aliases: ['py', 'pyen', 'phuyen', 'phu yen', 'phú yên'],
    isActive: true,
    schedule: { day: 'monday', order: 1 },
  },
  {
    name: 'Bình Định',
    region: 'central',
    aliases: ['bd', 'bdinh', 'binhdinh', 'binh dinh', 'bình định'],
    isActive: true,
    schedule: { day: 'thursday', order: 1 },
  },
  {
    name: 'Quảng Trị',
    region: 'central',
    aliases: ['qt', 'qtri', 'quangtri', 'quang tri', 'quảng trị'],
    isActive: true,
    schedule: { day: 'thursday', order: 2 },
  },
  {
    name: 'Quảng Bình',
    region: 'central',
    aliases: ['qb', 'qbinh', 'quangbinh', 'quang binh', 'quảng bình'],
    isActive: true,
    schedule: { day: 'thursday', order: 3 },
  },
  {
    name: 'Gia Lai',
    region: 'central',
    aliases: ['gl', 'glai', 'gialai', 'gia lai'],
    isActive: true,
    schedule: { day: 'friday', order: 1 },
  },
  {
    name: 'Ninh Thuận',
    region: 'central',
    aliases: ['nt', 'nthuan', 'ninhthuan', 'ninh thuan', 'ninh thuận'],
    isActive: true,
    schedule: { day: 'friday', order: 2 },
  },
  {
    name: 'Quảng Ngãi',
    region: 'central',
    aliases: ['qngai', 'quangngai', 'quang ngai', 'quảng ngãi'],
    isActive: true,
    schedule: { day: 'saturday', order: 2 },
  },
  {
    name: 'Đắk Nông',
    region: 'central',
    aliases: ['dn', 'dnong', 'daknong', 'dak nong', 'đắk nông'],
    isActive: true,
    schedule: { day: 'saturday', order: 3 },
  },
  {
    name: 'Kon Tum',
    region: 'central',
    aliases: ['kt', 'ktum', 'kontum', 'kon tum'],
    isActive: true,
    schedule: { day: 'sunday', order: 1 },
  },

  // Miền Bắc
  {
    name: 'Miền Bắc',
    region: 'north',
    aliases: [
      'mb',
      'mienbac',
      'miền bắc',
      'hanoi',
      'hn',
      'hà nội',
      'daibac',
      'dbac',
      'đài bắc',
      'đài miền bắc',
      'db',
    ],
    isActive: true,
    schedule: { day: 'daily', order: 1 },
    stations: [
      { name: 'Hà Nội', isActive: true },
      { name: 'Quảng Ninh', isActive: true },
      { name: 'Bắc Ninh', isActive: true },
      { name: 'Hải Phòng', isActive: true },
      { name: 'Nam Định', isActive: true },
      { name: 'Thái Bình', isActive: true },
    ],
  },
]

export const defaultBetTypes = [
  {
    name: 'Đầu Đuôi',
    aliases: ['dd', 'dau duoi', 'đầu đuôi', 'head and tail'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['2 digits'],
    matchingDraw: {
      south: {
        head: { prize: 'eighth', count: 1 },
        tail: { prize: 'special', count: 1 },
      },
      central: {
        head: { prize: 'eighth', count: 1 },
        tail: { prize: 'special', count: 1 },
      },
      north: {
        head: { prize: 'seventh', count: 4 },
        tail: { prize: 'special', count: 1 },
      },
    },
    combinations: {
      south: 2,
      central: 2,
      north: 5,
    },
    matchingMethod: 'Match the last 2 digits of the draw',
    payoutRate: 75,
    isActive: true,
  },
  {
    name: 'Xỉu chủ',
    aliases: ['xc', 'x', 'xiu chu', 'xiuchu', 'three digits'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['3 digits'],
    matchingDraw: {
      south: {
        head: { prize: 'seventh', count: 1 },
        tail: { prize: 'special', count: 1 },
      },
      central: {
        head: { prize: 'seventh', count: 1 },
        tail: { prize: 'special', count: 1 },
      },
      north: {
        head: { prize: 'sixth', count: 3 },
        tail: { prize: 'special', count: 1 },
      },
    },
    combinations: {
      south: 2,
      central: 2,
      north: 4,
    },
    matchingMethod: 'Match the last 3 digits of the draw',
    payoutRate: 650,
    isActive: true,
  },
  {
    name: 'Đầu',
    aliases: ['dau', 'đầu', 'head'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['2 digits', '3 digits'],
    matchingDraw: {
      '2 digits': {
        south: { prize: 'eighth', count: 1 },
        central: { prize: 'eighth', count: 1 },
        north: { prize: 'seventh', count: 4 },
      },
      '3 digits': {
        south: { prize: 'seventh', count: 1 },
        central: { prize: 'seventh', count: 1 },
        north: { prize: 'sixth', count: 3 },
      },
    },
    combinations: {
      '2 digits': {
        south: 1,
        central: 1,
        north: 4,
      },
      '3 digits': {
        south: 1,
        central: 1,
        north: 3,
      },
    },
    matchingMethod: 'Match the last 2 or 3 digits of the draw',
    payoutRate: {
      '2 digits': 75,
      '3 digits': 650,
    },
    isActive: true,
  },
  {
    name: 'Đuôi',
    aliases: ['duoi', 'dui', 'đuôi', 'tail'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['2 digits', '3 digits'],
    matchingDraw: {
      '2 digits': {
        south: { prize: 'special', count: 1 },
        central: { prize: 'special', count: 1 },
        north: { prize: 'special', count: 1 },
      },
      '3 digits': {
        south: { prize: 'special', count: 1 },
        central: { prize: 'special', count: 1 },
        north: { prize: 'special', count: 1 },
      },
    },
    combinations: {
      '2 digits': {
        south: 1,
        central: 1,
        north: 1,
      },
      '3 digits': {
        south: 1,
        central: 1,
        north: 1,
      },
    },
    matchingMethod: 'Match the last 2 or 3 digits of the draw',
    payoutRate: {
      '2 digits': 75,
      '3 digits': 650,
    },
    isActive: true,
  },
  {
    name: 'Bao Lô',
    aliases: ['b', 'bao', 'bao lo', 'bao lô', 'cover all'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['2 digits', '3 digits', '4 digits'],
    matchingDraw: {
      '2 digits': {
        south: 'all prizes',
        central: 'all prizes',
        north: 'all prizes',
      },
      '3 digits': {
        south: 'all prizes except eighth',
        central: 'all prizes except eighth',
        north: 'all prizes except seventh',
      },
      '4 digits': {
        south: 'all prizes except eighth and seventh',
        central: 'all prizes except eighth and seventh',
        north: 'all prizes except seventh and sixth',
      },
    },
    combinations: {
      '2 digits': {
        south: 18,
        central: 18,
        north: 27,
      },
      '3 digits': {
        south: 17,
        central: 17,
        north: 23,
      },
      '4 digits': {
        south: 16,
        central: 16,
        north: 20,
      },
    },
    matchingMethod: 'Match the last 2, 3, or 4 digits of the draw',
    payoutRate: {
      '2 digits': 75,
      '3 digits': 650,
      '4 digits': 5500,
    },
    isActive: true,
  },
  {
    name: 'Đảo Bao Lô',
    aliases: ['daob', 'bdao', 'dao bao', 'dao bao lo', 'permutation cover'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['2 digits', '3 digits'],
    matchingDraw: {
      '2 digits': {
        south: 'all prizes',
        central: 'all prizes',
        north: 'all prizes',
      },
      '3 digits': {
        south: 'all prizes except eighth',
        central: 'all prizes except eighth',
        north: 'all prizes except seventh',
      },
    },
    combinations: {
      '2 digits': {
        south: 18,
        central: 18,
        north: 27,
      },
      '3 digits': {
        south: 17,
        central: 17,
        north: 23,
      },
    },
    matchingMethod: 'Match any permutation of the last N digits of the draw',
    payoutRate: {
      '2 digits': 75,
      '3 digits': 650,
    },
    isPermutation: true,
    isActive: true,
  },
  {
    name: 'Bao Lô 7',
    aliases: ['baobay', 'b7l', 'b7lo', 'bao lo 7', 'cover seven'],
    applicableRegions: ['south', 'central'],
    betRule: ['2 digits'],
    matchingDraw: {
      south: 'eighth, seventh, sixth, fifth, special prizes',
      central: 'eighth, seventh, sixth, fifth, special prizes',
    },
    combinations: {
      south: 7,
      central: 7,
    },
    matchingMethod: 'Match the last 2 digits of specific prizes',
    payoutRate: 75,
    isActive: true,
  },
  {
    name: 'Bao Lô 8',
    aliases: ['baotam', 'b8l', 'b8lo', 'bao lo 8', 'cover eight'],
    applicableRegions: ['north'],
    betRule: ['2 digits'],
    matchingDraw: {
      north: 'seventh, sixth, special prizes',
    },
    combinations: {
      north: 8,
    },
    matchingMethod: 'Match the last 2 digits of specific prizes',
    payoutRate: 75,
    isActive: true,
  },
  {
    name: 'Bao Lô 7 Đảo',
    aliases: ['b7ld', 'b7ldao', 'cover seven permutation'],
    applicableRegions: ['south', 'central'],
    betRule: ['2 digits'],
    matchingDraw: {
      south: 'eighth, seventh, sixth, fifth, special prizes',
      central: 'eighth, seventh, sixth, fifth, special prizes',
    },
    combinations: {
      south: 7,
      central: 7,
    },
    matchingMethod:
      'Match any permutation of the last 2 digits of specific prizes',
    payoutRate: 75,
    isPermutation: true,
    isActive: true,
  },
  {
    name: 'Bao Lô 8 Đảo',
    aliases: ['b8ld', 'b8ldao', 'cover eight permutation'],
    applicableRegions: ['north'],
    betRule: ['2 digits'],
    matchingDraw: {
      north: 'seventh, sixth, special prizes',
    },
    combinations: {
      north: 8,
    },
    matchingMethod:
      'Match any permutation of the last 2 digits of specific prizes',
    payoutRate: 75,
    isPermutation: true,
    isActive: true,
  },
  {
    name: 'Đá',
    aliases: ['da', 'dv'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['2 digits'],
    matchingDraw: {
      south: 'all prizes',
      central: 'all prizes',
      north: 'all prizes',
    },
    combinations: {
      south: 18,
      central: 18,
      north: 27,
    },
    matchingMethod: 'At least 2 betted numbers match the draw',
    payoutRate: {
      bridgeOneStation: 750,
      bridgeTwoStations: 550,
      bridgeNorth: 650,
    },
    specialCalc: 'bridge',
    isActive: true,
  },
  {
    name: 'Đảo Xỉu Chủ',
    aliases: ['daoxc', 'dxc', 'xcd', 'xcdao', 'permutation three digits'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['3 digits'],
    matchingDraw: {
      south: {
        head: { prize: 'seventh', count: 1 },
        tail: { prize: 'special', count: 1 },
      },
      central: {
        head: { prize: 'seventh', count: 1 },
        tail: { prize: 'special', count: 1 },
      },
      north: {
        head: { prize: 'sixth', count: 3 },
        tail: { prize: 'special', count: 1 },
      },
    },
    combinations: {
      south: 2,
      central: 2,
      north: 4,
    },
    matchingMethod: 'Match any permutation of the last 3 digits of the draw',
    payoutRate: 650,
    isPermutation: true,
    isActive: true,
  },
  {
    name: 'Đảo Xỉu Chủ Đầu',
    aliases: ['dxcdau', 'daodau', 'ddau', 'permutation head'],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['3 digits'],
    matchingDraw: {
      south: { prize: 'seventh', count: 1 },
      central: { prize: 'seventh', count: 1 },
      north: { prize: 'sixth', count: 3 },
    },
    combinations: {
      south: 1,
      central: 1,
      north: 3,
    },
    matchingMethod:
      'Match any permutation of the last 3 digits of the head prize',
    payoutRate: 650,
    isPermutation: true,
    isActive: true,
  },
  {
    name: 'Đảo Xỉu Chủ Đuôi',
    aliases: [
      'dxcduoi',
      'daoduoi',
      'daodui',
      'dduoi',
      'ddui',
      'permutation tail',
    ],
    applicableRegions: ['south', 'central', 'north'],
    betRule: ['3 digits'],
    matchingDraw: {
      south: { prize: 'special', count: 1 },
      central: { prize: 'special', count: 1 },
      north: { prize: 'special', count: 1 },
    },
    combinations: {
      south: 1,
      central: 1,
      north: 1,
    },
    matchingMethod:
      'Match any permutation of the last 3 digits of the special prize',
    payoutRate: 650,
    isPermutation: true,
    isActive: true,
  },
  {
    name: 'Nhất To',
    aliases: ['nt', 'nto', 'nhatto', 'first prize'],
    applicableRegions: ['north'],
    betRule: ['2 digits', '3 digits', '4 digits'],
    matchingDraw: {
      north: { prize: 'first', count: 1 },
    },
    combinations: {
      north: 1,
    },
    matchingMethod: 'Match the last N digits of the first prize',
    payoutRate: {
      '2 digits': 75,
      '3 digits': 650,
      '4 digits': 5500,
    },
    isActive: true,
  },
]

export const defaultNumberCombinations = [
  {
    name: 'Kéo',
    aliases: ['keo', 'sequence'],
    definition:
      'Chọn số bắt đầu, số tiếp theo và số kết thúc để tạo một dãy số',
    syntax: '[startNumber]/[nextNumber]keo[endNumber]',
    applicableBetTypes: ['dau', 'duoi', 'dd', 'xc'],
    examples: [
      '10/20keo90 (sequence: 10, 20, 30, 40, 50, 60, 70, 80, 90)',
      '10/11keo19 (sequence: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)',
      '111/222keo999 (sequence: 111, 222, 333, 444, 555, 666, 777, 888, 999)',
    ],
    calculationMethod:
      'Let startNumber=A, nextNumber=B, endNumber=C. Step size D = B-A. Number of variations = (C-A)/D + 1',
    isActive: true,
  },
  {
    name: 'Tài',
    aliases: ['tai', 'high'],
    definition: 'Bao gồm 50 số từ 50 đến 99',
    syntax: 'tai',
    applicableBetTypes: ['dau', 'duoi', 'dd'],
    examples: ['tai (numbers: 50, 51, 52, ..., 99)'],
    calculationMethod: 'Fixed set of 50 numbers from 50 to 99',
    isActive: true,
  },
  {
    name: 'Xỉu',
    aliases: ['xiu', 'low'],
    definition: 'Bao gồm 50 số từ 00 đến 49',
    syntax: 'xiu',
    applicableBetTypes: ['dau', 'duoi', 'dd'],
    examples: ['xiu (numbers: 00, 01, 02, ..., 49)'],
    calculationMethod: 'Fixed set of 50 numbers from 00 to 49',
    isActive: true,
  },
  {
    name: 'Chẵn',
    aliases: ['chan', 'even'],
    definition: 'Bao gồm 50 số chẵn từ 00 đến 98',
    syntax: 'chan',
    applicableBetTypes: ['dau', 'duoi', 'dd'],
    examples: ['chan (numbers: 00, 02, 04, ..., 98)'],
    calculationMethod: 'Fixed set of 50 even numbers from 00 to 98',
    isActive: true,
  },
  {
    name: 'Lẻ',
    aliases: ['le', 'odd'],
    definition: 'Bao gồm 50 số lẻ từ 01 đến 99',
    syntax: 'le',
    applicableBetTypes: ['dau', 'duoi', 'dd'],
    examples: ['le (numbers: 01, 03, 05, ..., 99)'],
    calculationMethod: 'Fixed set of 50 odd numbers from 01 to 99',
    isActive: true,
  },
  {
    name: 'Chẵn Chẵn',
    aliases: ['chanchan', 'even-even'],
    definition: 'Bao gồm 25 số có cả hai chữ số đều chẵn',
    syntax: 'chanchan',
    applicableBetTypes: ['dau', 'duoi', 'dd'],
    examples: [
      'chanchan (numbers: 00, 02, 04, 06, 08, 20, 22, 24, 26, 28, ...)',
    ],
    calculationMethod: 'Fixed set of 25 numbers where both digits are even',
    isActive: true,
  },
  {
    name: 'Lẻ Lẻ',
    aliases: ['lele', 'odd-odd'],
    definition: 'Bao gồm 25 số có cả hai chữ số đều lẻ',
    syntax: 'lele',
    applicableBetTypes: ['dau', 'duoi', 'dd'],
    examples: ['lele (numbers: 11, 13, 15, 17, 19, 31, 33, 35, 37, 39, ...)'],
    calculationMethod: 'Fixed set of 25 numbers where both digits are odd',
    isActive: true,
  },
  {
    name: 'Chẵn Lẻ',
    aliases: ['chanle', 'even-odd'],
    definition: 'Bao gồm 25 số có chữ số đầu là chẵn và chữ số thứ hai là lẻ',
    syntax: 'chanle',
    applicableBetTypes: ['dau', 'duoi', 'dd'],
    examples: ['chanle (numbers: 01, 03, 05, 07, 09, 21, 23, 25, 27, 29, ...)'],
    calculationMethod:
      'Fixed set of 25 numbers where first digit is even and second digit is odd',
    isActive: true,
  },
  {
    name: 'Lẻ Chẵn',
    aliases: ['lechan', 'odd-even'],
    definition: 'Bao gồm 25 số có chữ số đầu là lẻ và chữ số thứ hai là chẵn',
    syntax: 'lechan',
    applicableBetTypes: ['dau', 'duoi', 'dd'],
    examples: ['lechan (numbers: 10, 12, 14, 16, 18, 30, 32, 34, 36, 38, ...)'],
    calculationMethod:
      'Fixed set of 25 numbers where first digit is odd and second digit is even',
    isActive: true,
  },
]
